name: Secret Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret_scan:
    name: Run GitLeaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: false # Prevents pipeline failure on warnings
